include/signalrclient/signalr_value.h

Ignore the lack of copy/move constructors and assignment operator(s). Assume they will be added unless you have a specific reason for not wanting them!
Some example usage (ignore the lack of actual json serializer/deserializer):
```c++
class hub_protocol
{
public:
virtual std::string write_message(const signalr::value& object) = 0;
virtual signalr::value parse_message(const std::string& input) = 0;
};
class json_hub_protocol : public hub_protocol
{
public:
virtual std::string write_message(const signalr::value& object) override
{
std::string output = "{";
for (auto& member : object.get_properties())
{
auto propertyName = member.get_property_name();
if (propertyName == "type")
{
if (member.is_number())
{
output += "\"type\":";
output += std::to_string(member.as_int());
}
else
{
// error
} …
```

Provide an Object Model for sending/receiving messages

---

README.md
include/signalrclient/hub_connection.h
include/signalrclient/signalr_value.h
samples/HubConnectionSample/CMakeLists.txt
src/signalrclient/CMakeLists.txt
src/signalrclient/callback_manager.cpp
src/signalrclient/callback_manager.h
src/signalrclient/hub_connection.cpp
src/signalrclient/hub_connection_impl.cpp
src/signalrclient/hub_connection_impl.h
src/signalrclient/signalr_value.cpp
test/signalrclienttests/callback_manager_tests.cpp
test/signalrclienttests/hub_connection_impl_tests.cpp

Changed `signalr::type` enum to `signalr::value_type`. GCC complained about `signalr::type signalr::value::type()` having the same name.

Replace web::json with signalr::value on public API

---

.azure/default-build.yml
CMakeLists.txt
azure-pipelines.yml
include/signalrclient/_exports.h
include/signalrclient/hub_connection.h
include/signalrclient/hub_connection_builder.h
include/signalrclient/signalr_client_config.h
src/signalrclient/connection_impl.cpp
src/signalrclient/connection_impl.h
src/signalrclient/default_websocket_client.cpp
src/signalrclient/hub_connection.cpp
src/signalrclient/hub_connection_builder.cpp
src/signalrclient/hub_connection_impl.cpp
src/signalrclient/hub_connection_impl.h
src/signalrclient/negotiate.cpp
src/signalrclient/negotiation_response.h
src/signalrclient/signalr_client_config.cpp
src/signalrclient/transport_factory.cpp
src/signalrclient/transport_factory.h
src/signalrclient/websocket_transport.cpp
src/signalrclient/websocket_transport.h
test/signalrclienttests/connection_impl_tests.cpp
test/signalrclienttests/hub_connection_tests.cpp
test/signalrclienttests/logger_tests.cpp
test/signalrclienttests/websocket_transport_tests.cpp

- And flow config to websockets transport
- Added new AzDO pipeline builds that don't compile with the cpprestsdk
Fixes https://github.com/dotnet/aspnetcore/issues/8718

Build without CPPRestSDK

---

include/signalrclient/signalr_value.h
src/signalrclient/json_hub_protocol.cpp
src/signalrclient/json_hub_protocol.h
src/signalrclient/signalr_value.cpp

Because we're using a union for the internal storage, we need to manually control the destruction of the storage. One case that was missed was during assignment if `this` already contained an object then we wouldn't destruct the internal storage when it was being replaced.
Also, snuck in a small change to remove a `substr` in the `json_hub_protocol`. Small perf gains 😄

Fix leak on assignment

---

azure-pipelines.yml

Thought we were being smart by using the vcpkg installed on the machines, but if there are breaking changes in vcpkg and our submodule isn't up to date, then it fails the build. So it's just easier to always create vcpkg and avoid these issues.

Always bootstrap vcpkg

---

src/signalrclient/CMakeLists.txt
test/signalrclienttests/CMakeLists.txt

When compile the client library with cpprestsdk from apt(maybe there are some other manual ways besides vcpkg), you will get the following link error:
```
/usr/bin/ld: CMakeFiles/signalrclienttests.dir/connection_impl_tests.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
```
The compiler is `gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
This commit fixed the problem.

Fix linking error when using cpprestsdk from apt

---

CMakeLists.txt
src/signalrclient/CMakeLists.txt

`If no type is given explicitly the type is STATIC or SHARED based on whether the current value of the variable BUILD_SHARED_LIBS is ON.`

Change library type

---

third_party_code/jsoncpp/jsoncpp.cpp

Disable the warning when a 32-bit float is returned which is treated as an error and prevents x86-Release config from building.

Disable C4378 for x86-Release

---

src/signalrclient/default_http_client.cpp
src/signalrclient/negotiate.cpp

Propagate http timeout configuration to the negotiate request.
Modify the timeout monitor in default_http_client so that task
is completed as soon as result is handled.

Better http request timeout handling.

---

.azure/default-build.yml
azure-pipelines.yml
src/signalrclient/signalr_value.cpp
test/signalrclienttests/signalrclienttests.cpp
test/signalrclienttests/stdafx.h

Linux PR builds (with exit code 1 on leaks)
```
==77190== 
==77190== HEAP SUMMARY:
==77190==     in use at exit: 72,816 bytes in 2 blocks
==77190==   total heap usage: 53,321 allocs, 53,319 frees, 5,137,654 bytes allocated
==77190== 
==77190== 112 bytes in 1 blocks are definitely lost in loss record 1 of 2
==77190==    at 0x4C2E0EF: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==77190==    by 0x52EE9D7: signalr::value::operator=(signalr::value const&) (in /home/vsts/work/1/s/build.Release/bin/libsignalrclient.so)
==77190==    by 0x459D52: std::_Function_handler<void (signalr::value const&), hub_invocation_hub_connection_can_receive_multiple_messages_in_same_payload_Test::TestBody()::{lambda(signalr::value const&)#1}>::_M_invoke(std::_Any_data …
```

Add memory leak detection to testing

---

src/signalrclient/CMakeLists.txt

https://github.com/microsoft/vcpkg/issues/14860
Turned if off because it seemed like a nice flag to reduce compile size. Turns out, some libraries use the `typeid` feature which requires RTTI.

Add RTTI back

---

include/signalrclient/connection.h
include/signalrclient/signalr_value.h
include/signalrclient/websocket_client.h
src/signalrclient/callback_manager.cpp
src/signalrclient/callback_manager.h
src/signalrclient/connection.cpp
src/signalrclient/connection_impl.cpp
src/signalrclient/connection_impl.h
src/signalrclient/default_websocket_client.cpp
src/signalrclient/default_websocket_client.h
src/signalrclient/handshake_protocol.cpp
src/signalrclient/handshake_protocol.h
src/signalrclient/hub_connection_impl.cpp
src/signalrclient/hub_connection_impl.h
src/signalrclient/hub_protocol.h
src/signalrclient/json_hub_protocol.cpp
src/signalrclient/json_hub_protocol.h
src/signalrclient/signalr_value.cpp
src/signalrclient/transport.h
src/signalrclient/websocket_transport.cpp
src/signalrclient/websocket_transport.h
test/signalrclienttests/CMakeLists.txt
test/signalrclienttests/callback_manager_tests.cpp
test/signalrclienttests/connection_impl_tests.cpp
test/signalrclienttests/handshake_tests.cpp
test/signalrclienttests/json_hub_protocol_tests.cpp
test/signalrclienttests/test_websocket_client.cpp
test/signalrclienttests/test_websocket_client.h
test/signalrclienttests/websocket_transport_tests.cpp

Pre-req for MessagePack support

Fix the protocol abstraction so different protocols can be supported

---

include/signalrclient/connection.h
include/signalrclient/hub_connection.h
include/signalrclient/trace_level.h
samples/HubConnectionSample/HubConnectionSample.cpp
src/signalrclient/connection_impl.cpp
src/signalrclient/hub_connection_impl.cpp
src/signalrclient/logger.cpp
src/signalrclient/logger.h
src/signalrclient/websocket_transport.cpp
test/signalrclienttests/connection_impl_tests.cpp
test/signalrclienttests/hub_connection_tests.cpp
test/signalrclienttests/logger_tests.cpp
test/signalrclienttests/test_utils.cpp
test/signalrclienttests/test_utils.h
test/signalrclienttests/websocket_transport_tests.cpp

* Changed log levels to follow what we did in AspNetCore
* Added new overload for internal logger implementation to avoid unneeded allocations
```
template <size_t N>
void log(trace_level level, const char (&entry)[N]) const
```
* Added `is_enabled` checks to all currently allocating log calls (those that use `std::string` and `append`)
* Write directly to stream instead of making a temporary string for trace level string

Logging improvements

---

CMakeLists.txt
README.md
samples/HubConnectionSample/CMakeLists.txt
src/signalrclient/CMakeLists.txt
src/signalrclient/cmake/microsoft-signalr-config.in.cmake
src/signalrclient/microsoft-signalr-config.in.cmake
test/signalrclienttests/CMakeLists.txt

If you want to try this out, first run `vcpkg.exe remove microsoft-signalr:x64-windows`, then update the local portfile.cmake for microsoft-signalr as shown below, then run `vcpkg.exe install microsoft-signalr:x64-windows
When we update the portfile on vcpkg we'll need to do the below:
```
vcpkg_from_github(
OUT_SOURCE_PATH SOURCE_PATH
REPO aspnet/SignalR-Client-Cpp
REF ee5926183f16bea153bcb4ae5a9370884a9d07c1
SHA512 d65a354bff1c9d29f48046844d167fbded6bf35b5c9decadcda3ace8df79b26e51183f788b695ae5aed0afb4084b917f0a5a474a671757df6c688fe05172b6fb
HEAD_REF main
)
vcpkg_check_features(
OUT_FEATURE_OPTIONS FEATURE_OPTIONS
FEATURES
cpprestsdk USE_CPPRESTSDK
)
if("cpprestsdk" IN_LIST FEATURES AND VCPKG_TARGET_IS_UWP)
message(FATAL_ERROR "microsoft-signalr[cpprestsdk] is not supported on UWP, use …
```

Rename project to microsoft-signalr and add find_package cmake support

---

CMakeLists.txt
include/signalrclient/signalr_value.h
src/signalrclient/CMakeLists.txt
test/signalrclienttests/CMakeLists.txt

Remove `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` which exposed all classes to user code and compile the test project with the main libraries source instead of with the library reference.

Compile test project with source files instead of library reference

---

.azure/default-build.yml
azure-pipelines.yml

Gcc from brew has issues with Mac, so switching to bootstrapping vcpkg with clang, but clang can't build vcpkg on mac 10.14 so updating to 10.15. And 10.14 is going out of support in November looks like.

Update Mac machine to 10.15

---

include/signalrclient/http_client.h

[aspnetcore issue](https://github.com/dotnet/aspnetcore/issues/34070)
Fixed build error with g++ 11.1.0 on Arch Linux.
Added `exception` header include to the `include/signalrclient/http_client.h`.

Fix build of http client

---

include/signalrclient/cancellation_token.h
include/signalrclient/http_client.h
src/signalrclient/CMakeLists.txt
src/signalrclient/cancellation_token.cpp
src/signalrclient/cancellation_token_source.cpp
src/signalrclient/cancellation_token_source.h
src/signalrclient/connection_impl.cpp
src/signalrclient/connection_impl.h
src/signalrclient/default_http_client.cpp
src/signalrclient/default_http_client.h
src/signalrclient/hub_connection_impl.cpp
src/signalrclient/hub_connection_impl.h
src/signalrclient/negotiate.cpp
src/signalrclient/negotiate.h
src/signalrclient/websocket_transport.cpp
src/signalrclient/websocket_transport.h
test/signalrclienttests/CMakeLists.txt
test/signalrclienttests/cancellation_token_source_tests.cpp
test/signalrclienttests/connection_impl_tests.cpp
test/signalrclienttests/hub_connection_tests.cpp
test/signalrclienttests/negotiate_tests.cpp
test/signalrclienttests/stdafx.h
test/signalrclienttests/test_http_client.cpp
test/signalrclienttests/test_http_client.h
test/signalrclienttests/test_utils.cpp
test/signalrclienttests/test_websocket_client.h
test/signalrclienttests/websocket_transport_tests.cpp

Relies on https://github.com/aspnet/SignalR-Client-Cpp/pull/61 so that needs to go in first.
This adds a way to cancel an http request, such as if stop is called while negotiate is in-progress

Add public cancellation_token and pass to http_client

---

include/signalrclient/signalr_client_config.h

Calling convention on ctor emits a warning since it's ignored. This only fails in some environments for some reason.
PR mostly to check the build, will merge when green.

Fix calling convention on ctor

---

CMakeLists.txt

Vcpkg uses cmake 3.14 internally https://github.com/microsoft/vcpkg/issues/9803#issuecomment-577688479 (at least last year it did).
Using a lower version of cmake can cause issues, see https://github.com/dotnet/aspnetcore/issues/35059
So lets raise our minimum version.

Update CMake version

---

src/signalrclient/json_hub_protocol.cpp
src/signalrclient/messagepack_hub_protocol.cpp

There is a [bug in the VS 2017 compiler](https://developercommunity.visualstudio.com/t/the-compiler-emits-c2440-when-trying-to-static-cas/793475) that doesn't allow casting a double cast to an enum.
Plus C++ casts should be preferred over C casts as they provide better compile time type safety.
There might be casts I missed since there isn't a "find C casts" search (without coming up with a regex). But I did a quick scan of the protocol class which were the main culprits, and fixed the VS 2017 issue reported by PlayFab.

Prefer C++ casts over C casts

---

src/signalrclient/case_insensitive_comparison_utils.h

`binary_function` and `unary_function` are deprecated in C++11 and removed in C++17
https://en.cppreference.com/w/cpp/utility/functional/binary_function#:~:text=binary_function%20is%20a%20base%20class%20for%20creating%20function,and%20result_type%20-%20defined%20by%20the%20template%20parameters.
They also aren't needed so removing them.

Remove use of deprecated/removed types

---

src/signalrclient/connection_impl.cpp
src/signalrclient/default_http_client.cpp
src/signalrclient/default_http_client.h

i am using signalr-client-cpp in a project where the host can only connect through http-proxy. 
Before the ws-connection is established a http-connection is used to check the capabilities of the remote service. This connection did not use the specified proxy-configuration.

default_http_client is not using specified proxy

---

src/signalrclient/hub_connection_impl.cpp
src/signalrclient/json_helpers.cpp
src/signalrclient/json_helpers.h
src/signalrclient/json_hub_protocol.cpp
test/signalrclienttests/hub_connection_tests.cpp
test/signalrclienttests/json_hub_protocol_tests.cpp
test/signalrclienttests/messagepack_hub_protocol_tests.cpp

Technically just the change in hub_connection_impl is enough, but why not also stop our protocol impls from returning a null message as well.

Properly handle unknown hub message types

---

src/signalrclient/binary_message_parser.h
src/signalrclient/signalr_client_config.cpp
src/signalrclient/transport_factory.cpp

When I compile microsoft-signalr[core,messagepack] under Linux, the following problem occurs.
```
/mnt/vcpkg/buildtrees/microsoft-signalr/src/1.0-alpha4-e34fa42a98/src/signalrclient/binary_message_parser.h:13:62: error: ‘size_t’ has not been declared
/mnt/vcpkg/buildtrees/microsoft-signalr/src/1.0-alpha4-e34fa42a98/src/signalrclient/transport_factory.cpp:26:20: error: ‘runtime_error’ is not a member of ‘std’
Line 39:    26 |         throw std::runtime_error("not implemented");
```
Solve the above problem by adding the missing header file.

Fixed the missing header file problem when compiling under Linux
